name: Build macOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r exe_versions/requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --add-data "exe_versions/tomato.png:." --icon=exe_versions/tomato.png exe_versions/main.py

      - name: Create DMG
        run: |
          mkdir -p dist/dmg
          cp -r dist/main.app dist/dmg/
          hdiutil create -volname "Pomodoro" -srcfolder dist/dmg -ov -format UDZO dist/Pomodoro-v${{ github.run_number }}.dmg

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Pomodoro-v${{ github.run_number }}.dmg
          tag_name: v${{ github.run_number }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

