name: Build Linux App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r exe_versions/requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --add-data "exe_versions/tomato.png:." exe_versions/main.py

      - name: Create AppImage (optional, fallback to binary)
        run: |
          mkdir -p dist/appimage
          cp dist/main dist/appimage/
          chmod +x dist/appimage/main
          tar -czf dist/Pomodoro-v${{ github.run_number }}-linux.tar.gz -C dist appimage/main

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Pomodoro-v${{ github.run_number }}-linux.tar.gz
          tag_name: v${{ github.run_number }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

