name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r exe_versions/requirements.txt

      - name: Convert PNG to ICO icon
        run: |
          python -c "
from PIL import Image
import os
img = Image.open('exe_versions/tomato.png')
img = img.convert('RGBA')
img.save('exe_versions/icon.ico')
print('Icon created successfully')
          "

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --add-data "exe_versions/tomato.png;." --icon=exe_versions/icon.ico exe_versions/main.py

      - name: Get version and create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Pomodoro Release v${{ github.run_number }}
          body: Automated Windows EXE build
          draft: false
          prerelease: false

      - name: Upload to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/main.exe
          asset_name: Pomodoro-v${{ github.run_number }}.exe
          asset_content_type: application/octet-stream

